server:
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/identity_service"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "kuHxo8Dl9MNwLGfA8aBN24XzFC38jhkS3SoDxZNYzPcdprNiohVdKPWt13AHEQYe"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds