server:
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/identity_service"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
